version: '3.7'
services:
  #  chat-app-redis:
  #    image: 'redis:alpine'
  #    container_name: chat-app-redis
  #    environment:
  #      - ALLOW_EMPTY_PASSWORD=yes
  #    ports:
  #      - "6379:6379"
  #    networks:
  #      - chat-app-network
  chat-app-db:
    container_name: chat-app-db
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: chat-app
    ports:
      - "3308:3306"
    networks:
      - chat-app-network
    volumes:
      - /var/lib/mysql/chat-app/db:/var/lib/mysql
  chat-message-db:
    container_name: chat-message-db
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

    ports:
      - "27017:27017"
    networks:
      - chat-app-network
    volumes:
      - /data/db/chat-message/db:/data/db
#  chat-app-be:
#    depends_on:
#      - chat-app-db
#      - chat-app-redis
#    image: truongnh28/chat-app
#    container_name: chat-app-be
#    restart: always
#    ports:
#      - "8080:8080"
#    networks:
#      - chat-app-network
#  chat-app-fe:
#    depends_on:
#      - chat-app-db
#      - chat-app-redis
#      - chat-app-be
#    image: truongnh28/chat-app-fe
#    container_name: chat-app-fe
#    restart: always
#    ports:
#      - "3000:3000"
#    networks:
#      - chat-app-network
networks:
  chat-app-network: