@startuml
hide footbox

actor "User A"

"User A" -> "App Server": Sent a GET with JWT request to get friend list
"App Server" -> "Database": Check JWT BlackList
"App Server" -> "Database": Get friend list
"App Server" -> "User A": Return result to User A

@enduml